INSERT INTO billionaires (first_name, last_name, career) VALUES
  ('Aliko', 'Dangote', 'Billionaire Industrialist'),
  ('Bill', 'Gates', 'Billionaire Tech Entrepreneur'),
  ('Folrunsho', 'Alakija', 'Billionaire Oil Magnate');


 
INSERT INTO userDETAILSANDINFO VALUES(1, 'test',  'test2', 'password');
  
INSERT INTO CATEGORY VALUES(1, 'BAGS');
INSERT INTO CATEGORY VALUES(2, 'SHOES');
INSERT INTO CATEGORY VALUES(3, 'ELECTRONICS');
INSERT INTO CATEGORY VALUES(4, 'CLOTHES');

SELECT * FROM CATEGORY ORDER BY category_id;
  
  


INSERT INTO PRODUCTS  VALUES(1, 1,  'CK', 50);
INSERT INTO PRODUCTS VALUES(2 , 1, 'BAGGIT', 50);
INSERT INTO PRODUCTS VALUES(3, 2, 'ADDIDAS RUNNING SHOES', 50);
INSERT INTO PRODUCTS VALUES(4, 3, 'ONEPLUS 7', 60);
INSERT INTO PRODUCTS VALUES(5, 3, 'LG TV', 70);
INSERT INTO PRODUCTS VALUES(6, 4, 'WRANGLER JEANS', 80);
INSERT INTO PRODUCTS VALUES(7, 4, 'WRANGLER SHIRTS', 90);

SELECT * FROM PRODUCTS;
  
  

INSERT INTO ORDERCART   VALUES(1, 1,  '2019-05-14');
INSERT INTO ORDERCART   VALUES(2, 2,  '2019-06-14');
INSERT INTO ORDERCART   VALUES(3, 3,  '2019-07-14');
INSERT INTO ORDERCART   VALUES(4, 4,  '2019-08-14');
INSERT INTO ORDERCART   VALUES(5, 5,  '2019-09-14');
INSERT INTO ORDERCART   VALUES(6, 6,  '2019-10-14');

SELECT * FROM ORDERCART;
  